import type {
  DisclosureKind,
  DisclosureText,
  LocaleMessages,
  LocaleOverride,
  UiText,
} from "./types.js";

const en: LocaleMessages = {
  kinds: {
    chatbot: {
      label: "AI assistant",
      title: "You are chatting with an AI",
      body: "This assistant is an AI system, not a person. Its answers are generated automatically and can be wrong.",
    },
    generated: {
      label: "AI-generated",
      title: "AI-generated content",
      body: "This content was generated by an AI system.",
    },
    edited: {
      label: "AI-edited",
      title: "Edited with AI",
      body: "This content was edited or altered with an AI system.",
    },
    deepfake: {
      label: "Artificially generated",
      title: "Artificially generated or manipulated",
      body: "This content was generated or manipulated with AI. It may show people, places or events differently from how they really were.",
    },
    "emotion-recognition": {
      label: "Emotion recognition",
      title: "Emotion recognition is active",
      body: "This service uses an AI system that recognises emotions or intentions from your data.",
    },
    "biometric-categorisation": {
      label: "Biometric categorisation",
      title: "Biometric categorisation is active",
      body: "This service uses an AI system that assigns people to categories based on biometric data.",
    },
  },
  ui: {
    acknowledge: "Got it",
    details: "About this label",
    generatedWith: "Generated with {generator}",
    createdOn: "Created on {date}",
    humanReviewed: "Reviewed by a person",
    moreInfo: "How we use AI",
    close: "Close",
  },
};

const de: LocaleMessages = {
  kinds: {
    chatbot: {
      label: "KI-Assistent",
      title: "Sie chatten mit einer KI",
      body: "Dieser Assistent ist ein KI-System und kein Mensch. Seine Antworten werden automatisch erzeugt und können falsch sein.",
    },
    generated: {
      label: "KI-generiert",
      title: "KI-generierter Inhalt",
      body: "Dieser Inhalt wurde von einem KI-System erzeugt.",
    },
    edited: {
      label: "Mit KI bearbeitet",
      title: "Mit KI bearbeitet",
      body: "Dieser Inhalt wurde mit einem KI-System bearbeitet oder verändert.",
    },
    deepfake: {
      label: "Künstlich erzeugt",
      title: "Künstlich erzeugt oder verändert",
      body: "Dieser Inhalt wurde mit KI erzeugt oder verändert. Er kann Personen, Orte oder Ereignisse anders zeigen, als sie wirklich waren.",
    },
    "emotion-recognition": {
      label: "Emotionserkennung",
      title: "Emotionserkennung ist aktiv",
      body: "Dieser Dienst setzt ein KI-System ein, das aus Ihren Daten Emotionen oder Absichten erkennt.",
    },
    "biometric-categorisation": {
      label: "Biometrische Kategorisierung",
      title: "Biometrische Kategorisierung ist aktiv",
      body: "Dieser Dienst setzt ein KI-System ein, das Personen anhand biometrischer Daten Kategorien zuordnet.",
    },
  },
  ui: {
    acknowledge: "Verstanden",
    details: "Über diese Kennzeichnung",
    generatedWith: "Erzeugt mit {generator}",
    createdOn: "Erstellt am {date}",
    humanReviewed: "Von einem Menschen geprüft",
    moreInfo: "Wie wir KI einsetzen",
    close: "Schliessen",
  },
};

const fr: LocaleMessages = {
  kinds: {
    chatbot: {
      label: "Assistant IA",
      title: "Vous discutez avec une IA",
      body: "Cet assistant est un système d’IA, pas une personne. Ses réponses sont générées automatiquement et peuvent être erronées.",
    },
    generated: {
      label: "Généré par IA",
      title: "Contenu généré par IA",
      body: "Ce contenu a été généré par un système d’IA.",
    },
    edited: {
      label: "Modifié par IA",
      title: "Modifié avec l’IA",
      body: "Ce contenu a été modifié ou altéré à l’aide d’un système d’IA.",
    },
    deepfake: {
      label: "Généré artificiellement",
      title: "Généré ou manipulé artificiellement",
      body: "Ce contenu a été généré ou manipulé avec l’IA. Il peut montrer des personnes, des lieux ou des événements autrement qu’ils n’ont réellement été.",
    },
    "emotion-recognition": {
      label: "Reconnaissance des émotions",
      title: "La reconnaissance des émotions est active",
      body: "Ce service utilise un système d’IA qui reconnaît des émotions ou des intentions à partir de vos données.",
    },
    "biometric-categorisation": {
      label: "Catégorisation biométrique",
      title: "La catégorisation biométrique est active",
      body: "Ce service utilise un système d’IA qui classe les personnes dans des catégories à partir de données biométriques.",
    },
  },
  ui: {
    acknowledge: "Compris",
    details: "À propos de ce label",
    generatedWith: "Généré avec {generator}",
    createdOn: "Créé le {date}",
    humanReviewed: "Vérifié par une personne",
    moreInfo: "Comment nous utilisons l’IA",
    close: "Fermer",
  },
};

const it: LocaleMessages = {
  kinds: {
    chatbot: {
      label: "Assistente IA",
      title: "Stai parlando con un’IA",
      body: "Questo assistente è un sistema di IA, non una persona. Le sue risposte sono generate automaticamente e possono essere sbagliate.",
    },
    generated: {
      label: "Generato con IA",
      title: "Contenuto generato con IA",
      body: "Questo contenuto è stato generato da un sistema di IA.",
    },
    edited: {
      label: "Modificato con IA",
      title: "Modificato con l’IA",
      body: "Questo contenuto è stato modificato o alterato con un sistema di IA.",
    },
    deepfake: {
      label: "Generato artificialmente",
      title: "Generato o manipolato artificialmente",
      body: "Questo contenuto è stato generato o manipolato con l’IA. Può mostrare persone, luoghi o eventi in modo diverso da come sono stati realmente.",
    },
    "emotion-recognition": {
      label: "Riconoscimento delle emozioni",
      title: "Il riconoscimento delle emozioni è attivo",
      body: "Questo servizio utilizza un sistema di IA che riconosce emozioni o intenzioni a partire dai tuoi dati.",
    },
    "biometric-categorisation": {
      label: "Categorizzazione biometrica",
      title: "La categorizzazione biometrica è attiva",
      body: "Questo servizio utilizza un sistema di IA che assegna le persone a categorie in base a dati biometrici.",
    },
  },
  ui: {
    acknowledge: "Ho capito",
    details: "Informazioni su questa etichetta",
    generatedWith: "Generato con {generator}",
    createdOn: "Creato il {date}",
    humanReviewed: "Verificato da una persona",
    moreInfo: "Come usiamo l’IA",
    close: "Chiudi",
  },
};

const registry = new Map<string, LocaleMessages>([
  ["en", en],
  ["de", de],
  ["fr", fr],
  ["it", it],
]);

/** The locales bundled with the free package. */
export const BUILT_IN_LOCALES = ["en", "de", "fr", "it"] as const;

/**
 * Adds or replaces a locale, e.g. one of the 24 EU languages from Witness Pro.
 * A partial override is merged over the existing locale of that code, or over English.
 */
export function registerLocale(code: string, messages: LocaleMessages | LocaleOverride): void {
  const key = code.toLowerCase();
  const base = registry.get(key) ?? registry.get(key.split("-")[0] ?? "") ?? en;
  registry.set(key, mergeMessages(base, messages));
}

/** Codes of all registered locales. */
export function registeredLocales(): string[] {
  return [...registry.keys()];
}

/**
 * Picks the best registered locale for a tag such as "de-CH" or a list of tags such as
 * `navigator.languages`. Falls back to English.
 */
export function resolveLocale(input?: string | readonly string[] | null): string {
  const tags = input == null ? [] : typeof input === "string" ? [input] : input;
  for (const tag of tags) {
    const lower = tag.toLowerCase();
    if (registry.has(lower)) return lower;
    const language = lower.split("-")[0] ?? "";
    if (registry.has(language)) return language;
  }
  return "en";
}

/** All messages of a locale, with an optional override merged in. */
export function getMessages(
  locale?: string | readonly string[] | null,
  override?: LocaleOverride,
): LocaleMessages {
  const messages = registry.get(resolveLocale(locale)) ?? en;
  return override ? mergeMessages(messages, override) : messages;
}

/** Wording for one disclosure kind. */
export function disclosureText(
  kind: DisclosureKind,
  locale?: string | readonly string[] | null,
  override?: LocaleOverride,
): DisclosureText {
  return getMessages(locale, override).kinds[kind];
}

/** Replaces `{name}` placeholders. Unknown placeholders stay as they are. */
export function format(template: string, values: Record<string, string | undefined>): string {
  return template.replace(/\{(\w+)\}/g, (match, name: string) => values[name] ?? match);
}

function mergeMessages(
  base: LocaleMessages,
  override: LocaleMessages | LocaleOverride,
): LocaleMessages {
  const kinds = { ...base.kinds };
  for (const [kind, text] of Object.entries(override.kinds ?? {})) {
    const key = kind as DisclosureKind;
    kinds[key] = { ...base.kinds[key], ...(text as Partial<DisclosureText>) };
  }
  const ui: UiText = { ...base.ui, ...(override.ui ?? {}) };
  return { kinds, ui };
}
